### ISSUE TITLE
Unsharp text

### ISSUE THREAD

**Issue by dmke** [NightCatSama/vue-slider-component#166]
Using `translateX`/`translateY` with fractional pixel values results in blurry text:

![image](https://user-images.githubusercontent.com/327411/37413610-bd8f9280-27a7-11e8-9885-b27770f32bd4.png)

```css
.left-dot  { transform: translateX(194.087px); }
.right-dot { transform: translateX(267.573px): }
```

Rounding it to the nearest integer gives a better picture:

![image](https://user-images.githubusercontent.com/327411/37413847-2f813a06-27a8-11e8-92d3-669472cf2eeb.png)

```css
.left-dot  { transform: translateX(194px); }
.right-dot { transform: translateX(268px): }
```

(both screen captures are from my old desktop monitor, with `window.devicePixelRatio === 1`).

I suggest rounding the final value in [`setTransform()`](https://github.com/NightCatSama/vue-slider-component/blob/50ca048/src/vue2-slider.vue#L751) to produce sharp text. This function rounds to the next `1/window.devicePixelRatio` pixel fraction (i.e. `roundToDPR(19.3)` on a HiDPI monitor = 19.5) and might be helpful:

```es6
const roundToDPR = (function() {
  const r = window.devicePixelRatio || 1
  return value => Math.round(value * r) / r
})()
```

What do you think?
