### ISSUE TITLE
There is a very small gap between the tooltip's balloon and the tooltip's handle in Chrome

### ISSUE THREAD

**Issue by xaviarnl** [NightCatSama/vue-slider-component#424]
In Chrome, there is a very small gap between the balloon of a tooltip, and its handle. You can see this on the live demo page, by setting the 'tooltip' setting to 'always', and optionally by zooming in:
![image](https://user-images.githubusercontent.com/17512042/70431905-53a8e300-1a7e-11ea-9463-5cf09d349d16.png)
In Firefox and IE11 I do not see this gap.

I have fixed it for now by adding this CSS rule:
.vue-slider-dot-tooltip-inner-top:after {
                top: 99.9%;
            }

I am using Vue 2.6.10, and version 3.0.44 of the slider.

**Comment by NightCatSama** [comment]
It seems to be a problem with chrome rendering. When using percentage positioning, there may be a deviation of 1px.

I can't think of a good solution for the time being, you can modify the style to hack this problem.
```css
.vue-slider-dot-tooltip-inner-top:after {
    transform: translate(-50%, -1px);
    // margin-top: -1px;
}
```
